import { useCallback } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { BillingEntry } from "./BillingLedger";
import { formatZAR, formatDuration } from "@/lib/formatters";
import { FileText } from "lucide-react";

interface InvoiceGeneratorProps {
  entries: BillingEntry[];
  firmName?: string;
  userName?: string;
}

export function InvoiceGenerator({ entries, firmName, userName }: InvoiceGeneratorProps) {
  const generateInvoice = useCallback(() => {
    if (entries.length === 0) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const now = new Date();
    const invoiceNo = `INV-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;

    // --- Header ---
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(30, 30, 40);
    doc.text("LEXFLOW", 20, 28);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 130);
    doc.text("BILLING INTELLIGENCE PLATFORM", 20, 34);

    // Invoice number + date (right-aligned)
    doc.setFontSize(9);
    doc.setTextColor(30, 30, 40);
    doc.text(`Invoice: ${invoiceNo}`, pageWidth - 20, 22, { align: "right" });
    doc.text(`Date: ${now.toLocaleDateString("en-ZA", { day: "2-digit", month: "long", year: "numeric" })}`, pageWidth - 20, 28, { align: "right" });

    // Firm / practitioner info
    if (firmName || userName) {
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 70);
      let yPos = 46;
      if (firmName) {
        doc.setFont("helvetica", "bold");
        doc.text(firmName, 20, yPos);
        yPos += 6;
      }
      if (userName) {
        doc.setFont("helvetica", "normal");
        doc.text(userName, 20, yPos);
        yPos += 6;
      }
    }

    // --- Divider ---
    doc.setDrawColor(220, 220, 225);
    doc.setLineWidth(0.3);
    doc.line(20, 62, pageWidth - 20, 62);

    // --- Table ---
    const totalHours = entries.reduce((a, e) => a + e.duration, 0);
    const totalAmount = entries.reduce((a, e) => a + e.amount, 0);

    const tableData = entries.map((e) => [
      new Date(e.timestamp).toLocaleDateString("en-ZA", { day: "2-digit", month: "short", year: "numeric" }),
      e.clientName,
      e.matterDescription.length > 60 ? e.matterDescription.substring(0, 57) + "..." : e.matterDescription,
      formatDuration(e.duration),
      formatZAR(e.amount),
    ]);

    autoTable(doc, {
      startY: 68,
      head: [["Date", "Client", "Matter Description", "Duration", "Amount (ZAR)"]],
      body: tableData,
      foot: [[
        "", "", "TOTAL",
        formatDuration(totalHours),
        formatZAR(totalAmount),
      ]],
      theme: "plain",
      styles: {
        fontSize: 9,
        cellPadding: 5,
        lineColor: [230, 230, 235],
        lineWidth: 0.2,
        textColor: [40, 40, 50],
        font: "helvetica",
      },
      headStyles: {
        fillColor: [245, 245, 248],
        textColor: [100, 100, 110],
        fontStyle: "bold",
        fontSize: 7.5,
        cellPadding: 4,
      },
      footStyles: {
        fillColor: [30, 30, 40],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 10,
      },
      columnStyles: {
        0: { cellWidth: 28 },
        1: { cellWidth: 32 },
        2: { cellWidth: "auto" },
        3: { cellWidth: 22, halign: "right" },
        4: { cellWidth: 30, halign: "right" },
      },
      alternateRowStyles: {
        fillColor: [250, 250, 252],
      },
    });

    // --- Footer ---
    const finalY = (doc as any).lastAutoTable?.finalY || 200;
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 170);
    doc.text("Generated by LexFlow — Billing Intelligence Platform", 20, finalY + 16);
    doc.text("FICA Compliant | POPIA Compliant", 20, finalY + 21);
    doc.text(`${invoiceNo}`, pageWidth - 20, finalY + 16, { align: "right" });

    // --- Save ---
    doc.save(`${invoiceNo}.pdf`);
  }, [entries, firmName, userName]);

  return (
    <button
      onClick={generateInvoice}
      disabled={entries.length === 0}
      className="group flex items-center gap-3 px-8 py-3 bg-primary text-white hover:bg-primary/90 transition-all shadow-sm hover:shadow-md disabled:opacity-40 disabled:cursor-not-allowed"
    >
      <FileText size={18} strokeWidth={1.5} className="group-hover:-translate-y-0.5 transition-transform" />
      <span className="font-headline text-sm tracking-tight font-medium uppercase">Generate Invoice</span>
    </button>
  );
}
